### ISSUE TITLE
Exclude apps

### ISSUE THREAD

**Issue by keganlance** [Collinux/minimalist-launcher#6]
It would be really nice to have a feature to exclude certain apps. For example, by holding them and click on "hide". Reasoning behind this is the excess amount of bloatware apps yet also apps which don't have any functionality when launching except some configuration page.

**Comment by sgtpep** [comment]
I'm not the author, but it's possible to either uninstall, or disable any unwanted app, regardless of the launcher used.

**Comment by keganlance** [comment]
Thanks for your reply! Yet on many phones. There are some apps you simply can't disable or remove. And those will still mess up the launcher.

**Comment by Collinux** [comment]
I understand the desire for this feature, the amount of bloatware on most non-Google phones is absolutely insane. 

This feature would have the following requirements:
- Long press listener would be needed on each item in the list
- Long press listener would open a dialog with a button to hide the application
- A settings activity + UI would need to display a list of hidden applications and have the option to un-hide applications
- The launcher would need to maintain a data set with the list of user selected hidden applications

Despite the need, I believe this would go against the central philosophy of the initial release due to the amount of extra UI elements, actvities, and handlers in the requirements. This would be a slippery slope for more features and it would drop support for earlier versions of Android.

You're welcome to fork this project and implement the features for your project or you can check of some of the other forks of this project, such as this one: https://github.com/light-launcher/Light-Android-Launcher
